Long-read SV support with Sniffles 2 (#263)
bihealth/snappy-pipeline pull request #264
Opened 2022-12-12 15:53 UTC by holtgrewe

2022-12-12 17:01 UTC, holtgrewe commented
@eudesbarbosa @Nicolai-vKuegelgen this one is ready for review

2022-12-13 11:30 UTC, eudesbarbosa commented on snappy_pipeline/workflows/ngs_mapping/Snakefile
> -    resources:
This looks off. Should it be something like below...
```
    resources:
        time=wf.get_resource("minimap2", "run", "time"),
        memory=wf.get_resource("minimap2", "run", "memory"),
        partition=wf.get_resource("minimap2", "run", "partition"),
    params:
        args=wf.substep_dispatch("minimap2", "get_args", "run"),

```

2022-12-13 11:31 UTC, eudesbarbosa commented on snappy_pipeline/workflows/ngs_mapping/__init__.py
> +            time="0-12:00:00",  # 2 days
Cosmetic: comment is wrong.

2022-12-13 11:32 UTC, eudesbarbosa commented on snappy_pipeline/workflows/wgs_sv_calling/__init__.py
> +    - ``"sniffles"``, ``"sniffles2"``
Maybe new line to keep it consistent with the rest?

2022-12-13 11:33 UTC, eudesbarbosa commented on snappy_pipeline/workflows/wgs_sv_calling/__init__.py
> +      tandem_repeats: /fast/groups/cubi/work/projects/biotools/sniffles2/trf/GRCh37/human_hs37d5.trf.bed
Probably tag it with 'REQUIRED' so it goes to local config?

2022-12-13 11:35 UTC, eudesbarbosa commented on snappy_wrappers/wrappers/minimap2/wrapper.py
> +pdb.set_trace()
Construction leftover?

2022-12-13 11:43 UTC, eudesbarbosa requested changes
Looks good. I marked a few things for clarification or cosmetic reasons.

2022-12-13 12:02 UTC, holtgrewe commented
Should be fixed now.

2022-12-13 13:39 UTC, eudesbarbosa approved these changes
LGTM

2022-12-13 13:41 UTC, merged