Fixing Mantis
bihealth/snappy-pipeline pull request #427
Opened 2023-08-07 12:43 UTC by giacuong171

- Testing mantis
- Rewrite pipeline

2023-08-14 11:02 UTC, ericblanc20 requested changes

2023-08-14 11:02 UTC, ericblanc20 commented on snappy_pipeline/workflows/somatic_msi_calling/__init__.py
> +    "mantis_msi2": {
What is the format of the output? What is `result`, and what is `status`? Ideally, you want a 3rd output containing the minimal MSI/not MSI status in a format independent of the caller. That way, downstream steps can collect the main information without having to rely on the tool's specifics.

2023-08-14 12:26 UTC, giacuong171 commented on snappy_pipeline/workflows/somatic_msi_calling/__init__.py
> +    def get_normal_lib_name(self, wildcards):
mantis does use normal samples, as you can see in the wrapper.

2023-08-14 12:27 UTC, giacuong171 commented on snappy_pipeline/workflows/somatic_msi_calling/__init__.py
>      loci_bed: /fast/groups/cubi/projects/biotools/Mantis/appData/hg19/loci.bed  # REQUIRED
Yes. Should i provide it in the default config ?

2023-08-16 11:14 UTC, ericblanc20 commented on snappy_pipeline/workflows/somatic_msi_calling/__init__.py
>      loci_bed: /fast/groups/cubi/projects/biotools/Mantis/appData/hg19/loci.bed  # REQUIRED
I'd say: 
```
loci_bed: "" # For example: /fast/groups/cubi/projects/biotools/Mantis/appData/hg19/loci.bed for hg19 (=GRCh37 with chr prefix)
             # /fast/groups/cubi/projects/biotools/Mantis/appData.... for GRCh38
```

2024-04-17 12:10 UTC, ericblanc20 approved these changes

2024-04-17 12:11 UTC, merged