feat: 438 vep annotation order
bihealth/snappy-pipeline pull request #441
Opened 2023-09-13 13:36 UTC by ericblanc20

Impose user-defined annotation order for VEP.
Previously, the wrapper was using the default order, based on ENSEMBL canonical transcript.
Because of that choice, many variant were not uploaded to cBioPortal.

The default choice now prioritizes protein-coding genes with MANE transcripts.
Many variants are now recovered in cBioPortal views.

2023-09-13 16:37 UTC, mbenary requested changes
Just a few tiny things, sorry for being picky.

2023-09-13 16:37 UTC, mbenary commented on snappy_pipeline/workflows/somatic_variant_annotation/__init__.py
> +The ordering of features drinving the representative annotation choice is under user control.
Typo: 

> driving

2023-09-13 16:37 UTC, mbenary commented on snappy_wrappers/wrappers/vep/post_filter/wrapper.py
> +                codes[criterion] = get_value(criterion, fields[criterion])
Probably a very simple thing: Why is codes changed here? It's not used afterwards.

2023-09-14 07:23 UTC, ericblanc20 commented on snappy_pipeline/workflows/somatic_variant_annotation/__init__.py
> +      pick_order: ["biotype", "mane", "appris", "tsl", "ccds", "canonical", "rank", "length"]
This is the default order. In `check_config`, the code tests validity of all the options provided by the user in the yaml file

2023-09-14 09:54 UTC, mbenary approved these changes
LGTM

2023-09-14 10:05 UTC, merged