fix!: pin dependency version in all wrapper conda env yamls
bihealth/snappy-pipeline pull request #492
Opened 2024-03-22 13:57 UTC by tedil

This PR aims to increase reproducibility and is a precursor to be able to properly end-to-end test the pipeline.
All version specifications in the wrappers' environment.yaml files were pinned to one specific version, in a configuration that can actually be installed with mamba/conda and a strict channel priority (which is why sometimes the channel definitions were also changed).
This was done programmatically, with the exception of some wrappers for which manual intervention was required:
 - gcnv
 - jaffa/run
 - cnvetti/on_target/postprocess
 - svtk
 - scramble
 - link_in_bam
 - lohhla

Since there are no tests for the wrappers yet, I can't really be sure if this breaks anything, so I'd rather be cautious and assume that it does.

2024-04-02 13:39 UTC, Nicolai-vKuegelgen requested changes
From my understanding the 'r' channel should not be used anymore, also some packages use 'r' as a package name instead of r-base.

I don't think "http://conda.cubi.bihealth.org/cubiconda" is reachable from the outside, so relying on that here is a bit unfortunate (no easy way to fix this though, I guess)

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/bed_jaccard_operations/environment.yaml
> +  - r
remove

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/canvas/somatic_wgs/environment.yaml
> +  - r
remove

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/cbioportal/generate_cna/environment.yaml
> +  - r
remove

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/cbioportal/merge_tables/environment.yaml
> +  - r
remove

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/cnvetti/on_target/coverage/environment.yaml
> +  - r
remove

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/cnvetti/on_target/postprocess/environment.yaml
> +  - r
remove

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/cnvetti/on_target/postprocess/environment.yaml
> +  - r==4.2
should be r-base

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/cnvetti/wgs/environment.yaml
> +  - r
remove

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/cnvkit/environment.yaml
> +  - r
remove

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/cnvkit/postprocess/environment.yaml
> +  - r
remove

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/control_freec/environment.yaml
> +  - base
not sure this exists?

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/copywriter/environment.yaml
> +  - r==3.6
should be r-base

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/delly2/germline/environment.yaml
> +  - r
remove

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/dupradar/environment.yaml
> +  - r==4.3
r-base

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/epitoper/environment.yaml
> +  - r
remove

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/epitoper_par/environment.yaml
> +  - r
remove

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/fusioncatcher/run/environment.yaml
> +  - r
remove

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/gatk_hc_par/environment.yaml
> +  - r
remove

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/gatk_read_backed_phasing/environment.yaml
> +  - r
remove

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/gatk_read_backed_phasing_par/environment.yaml
> +  - r
remove

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/gatk_ug_par/environment.yaml
> +  - r
remove

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/gcnv/environment.yaml
> +  - r
remove

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/hts_screen/environment.yaml
> +  - r
remove

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/jaffa/run/environment.yaml
> +- r
remove

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/jannovar/environment.yaml
> +  - r
remove

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/manta/germline_wgs/environment.yaml
> +  - r
remove

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/manta/somatic_wgs/environment.yaml
> +  - r
remove

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/minialign/run/environment.yaml
> +  - r
remove

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/mutect/environment.yaml
> +  - r
remove

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/popdel/environment.yaml
> +  - r
remove

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/rnaqc/dupradar/environment.yaml
> +  - r==4.0
r-base

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/rnaqc/environment.yaml
> +  - r==4.0
r-base

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/scalpel/somatic/environment.yaml
> +  - r
remove

2024-04-02 13:39 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/signatures/deconstruct_sigs/environment.yaml
> +  - r==4.3
r-base

2024-04-02 13:44 UTC, Nicolai-vKuegelgen commented on snappy_wrappers/wrappers/gatk4_hc/environment.yaml
> +  - parallel==20221122
I have pinned version 20231122 in a local branch, I think that might better here

2024-04-09 15:47 UTC, Nicolai-vKuegelgen approved these changes
LGTM overall

However, this covers many more steps than I am familiar with, so can't guarantee that this won't break anything.

2024-04-18 13:36 UTC, ericblanc20 reviewed
Looks good to me

2024-04-18 13:36 UTC, ericblanc20 commented on snappy_wrappers/wrappers/scarHRD/environment.yaml
Is it possible to keep the comments here?

2024-04-18 13:36 UTC, ericblanc20 commented on snappy_wrappers/wrappers/sequenza/install/environment.yaml
Is it possible to keep the comments here?

2024-04-18 14:43 UTC, tedil commented on snappy_wrappers/wrappers/scarHRD/environment.yaml
Yes, good point!

2024-04-18 15:43 UTC, merged