Standarize imports.
bihealth/snappy-pipeline pull request #53
Opened 2021-03-29 08:37 UTC by eudesbarbosa

closes #52

2021-03-30 12:51 UTC, eudesbarbosa commented
@holtgrewe, quick overview:
1. I passed `isort` once, even though it has a slightly different style than `flake8`. We can solve the issues slowly as we move forward.
2. The new import should be part of the CI workflow now.
3. I also took some time to remove `token` from the code.

2021-04-01 07:47 UTC, holtgrewe requested changes
Looks good in general, just adress the points.

Please add isort to here:

- https://github.com/bihealth/repository-checklists/blob/main/Checklist-Python.md

2021-04-01 07:47 UTC, holtgrewe commented on README.rst
> +SNAPPY - SNAPPY Nucleic Acid Processing Pipeline
Adjust the `===`.

2021-04-01 07:47 UTC, holtgrewe commented on requirements/test.txt
> +isort==4.3.21
We have a space before `==` elsewhere.

2021-04-01 08:49 UTC, eudesbarbosa commented on requirements/test.txt
> +isort==4.3.21
Fixed.

2021-04-01 12:22 UTC, eudesbarbosa commented
Added the style checking to the list.

The last Codacy issue I cannot fix for the life of me...

2021-04-07 08:40 UTC, eudesbarbosa reviewed
ok

2021-04-07 08:46 UTC, eudesbarbosa commented
> 
> 
> Looks good in general, just adress the points.
> 
> Please add isort to here:
> 
>     * https://github.com/bihealth/repository-checklists/blob/main/Checklist-Python.md

All done. New PR: https://github.com/bihealth/repository-checklists/pull/1

2021-04-07 20:36 UTC, holtgrewe approved these changes

2021-04-07 20:37 UTC, holtgrewe commented
Can be merged IMO, make sure to squash ;-) 🔨

2021-04-08 06:51 UTC, merged